/**
 * Fictional cigarettes — SPEC.md §12, §13.
 *
 * Six originals, no real brands (§84). Each one differs in smoke, ember, burn, ash,
 * sound and which environments it suits, so "trying another one" is a real change of
 * texture rather than a recoloured sprite.
 */

import { rgb } from '@puffly/shared';
import type { CigaretteContent } from '@puffly/game-core';

const COMMON_EVENTS = ['wind', 'ember_flare', 'light_change', 'shadow_change', 'ambient_event'];
const ASHY_EVENTS = [...COMMON_EVENTS, 'ash_fall', 'smoke_swirl'];
const STORMY_EVENTS = [...ASHY_EVENTS, 'wind', 'environment_noise'];

export const CIGARETTES: CigaretteContent[] = [
  {
    id: 'classic',
    name: 'Classic',
    // The one everyone recognises: a narrow, lazy column off the cherry.
    character: 'column',
    burnDuration: { min: 168_000, max: 214_000 },
    puffProfile: {
      intensityMin: 0.34,
      intensityMax: 0.86,
      durationMin: 780,
      durationMax: 2100,
      savourMs: 0,
      loadPerPuff: 0.24,
      exhaleMs: 0,
    },
    smokeProfile: { density: 0.92, turbulence: 0.9, riseSpeed: 0.3, dispersion: 0.85 },
    emberProfile: { brightness: 0.74, flicker: 0.32, flareChance: 0.016 },
    ashProfile: { minLength: 0.022, maxLength: 0.072 },
    physical: {
      lengthMm: 84,
      ashGrams: 2.1,
      centerTempC: [700, 800],
      puffs: { target: 12, min: 8, max: 15 },
    },
    archive: { zhName: '原生卷烟', kind: 'inhale' },
    eventPool: ASHY_EVENTS,
    palette: {
      paper: rgb(238, 233, 222),
      band: rgb(196, 68, 52),
      filter: rgb(206, 150, 96),
      ash: rgb(122, 122, 128),
    },
    smokeStyleId: 'grey-classic',
    soundProfileId: 'draw-warm',
    environmentBias: ['quiet-room', 'late-night-desk', 'balcony'],
    unlock: { kind: 'default' },
  },
  {
    id: 'silver',
    name: 'Silver',
    // Wide, faint and slow: it fills the air and mostly refuses to be noticed.
    character: 'haze',
    burnDuration: { min: 150_000, max: 196_000 },
    puffProfile: {
      intensityMin: 0.28,
      intensityMax: 0.72,
      durationMin: 640,
      durationMax: 1700,
      savourMs: 0,
      loadPerPuff: 0.24,
      exhaleMs: 0,
    },
    smokeProfile: { density: 0.72, turbulence: 0.62, riseSpeed: 0.36, dispersion: 0.6 },
    emberProfile: { brightness: 0.66, flicker: 0.22, flareChance: 0.011 },
    ashProfile: { minLength: 0.018, maxLength: 0.058 },
    physical: {
      lengthMm: 99,
      ashGrams: 1.8,
      centerTempC: [690, 780],
      puffs: { target: 11, min: 8, max: 14 },
    },
    archive: { zhName: '细支淡烟', kind: 'inhale' },
    eventPool: COMMON_EVENTS,
    palette: {
      paper: rgb(246, 246, 248),
      band: rgb(150, 158, 168),
      filter: rgb(222, 224, 228),
      ash: rgb(150, 152, 158),
    },
    smokeStyleId: 'silver-veil',
    soundProfileId: 'draw-cool',
    environmentBias: ['neon-street', 'night-city'],
    unlock: { kind: 'sessions', count: 8 },
  },
  {
    id: 'night',
    name: 'Night',
    // Restless: the column rolls and eddies instead of climbing.
    character: 'curls',
    burnDuration: { min: 122_000, max: 164_000 },
    puffProfile: {
      intensityMin: 0.4,
      intensityMax: 0.94,
      durationMin: 900,
      durationMax: 2400,
      savourMs: 0,
      loadPerPuff: 0.26,
      exhaleMs: 0,
    },
    smokeProfile: { density: 1.08, turbulence: 1.24, riseSpeed: 0.24, dispersion: 1.05 },
    emberProfile: { brightness: 0.86, flicker: 0.44, flareChance: 0.026 },
    ashProfile: { minLength: 0.026, maxLength: 0.084 },
    physical: {
      lengthMm: 84,
      ashGrams: 2.0,
      centerTempC: [720, 800],
      puffs: { target: 13, min: 9, max: 16 },
    },
    archive: { zhName: '深色短支', kind: 'inhale' },
    eventPool: STORMY_EVENTS,
    palette: {
      paper: rgb(196, 198, 210),
      band: rgb(38, 42, 62),
      filter: rgb(96, 92, 116),
      ash: rgb(88, 88, 96),
    },
    smokeStyleId: 'night-blue',
    soundProfileId: 'draw-deep',
    environmentBias: ['night-city', 'rainy-window'],
    unlock: { kind: 'sessions', count: 95 },
  },
  {
    id: 'long',
    name: 'Long',
    character: 'column',
    burnDuration: { min: 240_000, max: 312_000 },
    puffProfile: {
      intensityMin: 0.24,
      intensityMax: 0.64,
      durationMin: 1000,
      durationMax: 2600,
      savourMs: 0,
      loadPerPuff: 0.2,
      exhaleMs: 0,
    },
    smokeProfile: { density: 0.66, turbulence: 0.54, riseSpeed: 0.42, dispersion: 0.52 },
    emberProfile: { brightness: 0.6, flicker: 0.18, flareChance: 0.008 },
    ashProfile: { minLength: 0.03, maxLength: 0.108 },
    physical: {
      lengthMm: 100,
      ashGrams: 2.6,
      centerTempC: [690, 790],
      puffs: { target: 14, min: 10, max: 18 },
    },
    archive: { zhName: '长支慢燃', kind: 'inhale' },
    eventPool: ASHY_EVENTS,
    palette: {
      paper: rgb(240, 238, 232),
      band: rgb(120, 132, 118),
      filter: rgb(228, 214, 188),
      ash: rgb(132, 132, 134),
    },
    smokeStyleId: 'mist-thin',
    soundProfileId: 'draw-cool',
    environmentBias: ['balcony', 'mountain'],
    unlock: { kind: 'sessions', count: 190 },
  },
  {
    id: 'ember',
    name: 'Ember',
    // Balloons outward on the exhale and is gone, with sparks to cover for it.
    character: 'bloom',
    burnDuration: { min: 108_000, max: 146_000 },
    puffProfile: {
      intensityMin: 0.46,
      intensityMax: 1,
      durationMin: 620,
      durationMax: 1500,
      savourMs: 0,
      loadPerPuff: 0.3,
      exhaleMs: 0,
    },
    smokeProfile: { density: 1.16, turbulence: 1.42, riseSpeed: 0.34, dispersion: 1.2 },
    emberProfile: { brightness: 0.94, flicker: 0.52, flareChance: 0.042 },
    ashProfile: { minLength: 0.016, maxLength: 0.05 },
    physical: {
      lengthMm: 84,
      ashGrams: 1.9,
      centerTempC: [740, 800],
      puffs: { target: 13, min: 9, max: 16 },
    },
    archive: { zhName: '烈性短支', kind: 'inhale' },
    eventPool: STORMY_EVENTS,
    palette: {
      paper: rgb(232, 206, 176),
      band: rgb(214, 96, 40),
      filter: rgb(176, 92, 44),
      ash: rgb(104, 88, 82),
    },
    smokeStyleId: 'ember-warm',
    soundProfileId: 'draw-crackle',
    environmentBias: ['late-night-desk', 'mountain'],
    unlock: { kind: 'sessions', count: 40 },
  },
  {
    id: 'mist',
    name: 'Mist',
    // Cold and heavy: it pours off the cherry and lies on the table.
    character: 'curtain',
    burnDuration: { min: 196_000, max: 246_000 },
    puffProfile: {
      intensityMin: 0.2,
      intensityMax: 0.58,
      durationMin: 1100,
      durationMax: 2800,
      savourMs: 0,
      loadPerPuff: 0.22,
      exhaleMs: 0,
    },
    smokeProfile: { density: 1.3, turbulence: 0.42, riseSpeed: 0.16, dispersion: 1.35 },
    emberProfile: { brightness: 0.58, flicker: 0.14, flareChance: 0.006 },
    ashProfile: { minLength: 0.024, maxLength: 0.09 },
    physical: {
      lengthMm: 90,
      ashGrams: 2.3,
      centerTempC: [660, 740],
      puffs: { target: 10, min: 7, max: 13 },
    },
    archive: { zhName: '粗支厚烟', kind: 'inhale' },
    eventPool: [...COMMON_EVENTS, 'smoke_swirl', 'rain'],
    palette: {
      paper: rgb(228, 234, 236),
      band: rgb(132, 172, 178),
      filter: rgb(196, 210, 212),
      ash: rgb(140, 146, 150),
    },
    smokeStyleId: 'mist-thin',
    soundProfileId: 'draw-soft',
    environmentBias: ['rainy-window', 'mountain'],
    unlock: { kind: 'sessions', count: 65 },
  },
  {
    id: 'ryo',
    name: 'RYO',
    // Hand-rolled: looser tobacco, a shorter life, and an ash that will not stand up.
    character: 'curls',
    burnDuration: { min: 420_000, max: 480_000 },
    puffProfile: {
      intensityMin: 0.3,
      intensityMax: 0.8,
      durationMin: 700,
      durationMax: 1900,
      savourMs: 0,
      loadPerPuff: 0.2,
      exhaleMs: 0,
    },
    smokeProfile: { density: 0.86, turbulence: 1.1, riseSpeed: 0.34, dispersion: 0.9 },
    emberProfile: { brightness: 0.78, flicker: 0.36, flareChance: 0.02 },
    ashProfile: { minLength: 0.012, maxLength: 0.04 },
    physical: {
      lengthMm: 70,
      ashGrams: 2.4,
      centerTempC: [790, 850],
      puffs: { target: 11, min: 8, max: 14 },
    },
    archive: { zhName: '手卷', kind: 'inhale' },
    eventPool: ASHY_EVENTS,
    palette: {
      paper: rgb(244, 238, 224),
      band: rgb(126, 106, 78),
      filter: rgb(214, 198, 168),
      ash: rgb(140, 136, 132),
    },
    smokeStyleId: 'grey-classic',
    soundProfileId: 'draw-crackle',
    environmentBias: ['balcony', 'mountain', 'quiet-room'],
    unlock: { kind: 'sessions', count: 20 },
  },
  {
    id: 'cigarillo',
    name: 'Cigarillo',
    // Savoured, not inhaled: a slow ring, and the smoke lies rather than climbs.
    character: 'haze',
    burnDuration: { min: 1_020_000, max: 1_140_000 },
    puffProfile: {
      intensityMin: 0.22,
      intensityMax: 0.58,
      durationMin: 900,
      durationMax: 2200,
      savourMs: 2000,
      loadPerPuff: 0,
      exhaleMs: 2500,
    },
    smokeProfile: { density: 1.05, turbulence: 0.5, riseSpeed: 0.22, dispersion: 0.7 },
    emberProfile: { brightness: 0.62, flicker: 0.18, flareChance: 0.008 },
    ashProfile: { minLength: 0.02, maxLength: 0.06 },
    physical: {
      lengthMm: 90,
      ashGrams: 3.2,
      centerTempC: [720, 780],
      puffs: { target: 16, min: 12, max: 22 },
    },
    archive: { zhName: '小雪茄', kind: 'savor' },
    eventPool: COMMON_EVENTS,
    palette: {
      paper: rgb(122, 88, 56),
      band: rgb(196, 164, 118),
      filter: rgb(84, 58, 38),
      ash: rgb(118, 114, 112),
    },
    smokeStyleId: 'silver-veil',
    soundProfileId: 'draw-soft',
    environmentBias: ['late-night-desk', 'balcony'],
    unlock: { kind: 'sessions', count: 135 },
  },
  {
    id: 'cigar',
    name: 'Cigar',
    // The long one: a column of smoke, an ash you lean on, and half an hour of quiet.
    character: 'column',
    burnDuration: { min: 2_880_000, max: 3_120_000 },
    puffProfile: {
      intensityMin: 0.2,
      intensityMax: 0.52,
      durationMin: 1100,
      durationMax: 2400,
      savourMs: 2000,
      loadPerPuff: 0,
      exhaleMs: 2500,
    },
    smokeProfile: { density: 1.2, turbulence: 0.42, riseSpeed: 0.2, dispersion: 0.55 },
    emberProfile: { brightness: 0.6, flicker: 0.14, flareChance: 0.006 },
    ashProfile: { minLength: 0.03, maxLength: 0.12 },
    physical: {
      lengthMm: 140,
      ashGrams: 6.5,
      centerTempC: [780, 850],
      puffs: { target: 24, min: 18, max: 30 },
    },
    archive: { zhName: '雪茄', kind: 'savor' },
    eventPool: COMMON_EVENTS,
    palette: {
      paper: rgb(104, 72, 44),
      band: rgb(206, 176, 128),
      filter: rgb(64, 44, 30),
      ash: rgb(112, 108, 106),
    },
    smokeStyleId: 'night-blue',
    soundProfileId: 'draw-deep',
    environmentBias: ['night-city', 'mountain'],
    unlock: { kind: 'sessions', count: 250 },
  },
  {
    id: 'pipe',
    name: 'Pipe',
    // A bowl, not a rod: cool, low, and generous with the smoke it puts on the table.
    character: 'curtain',
    burnDuration: { min: 2_280_000, max: 2_520_000 },
    puffProfile: {
      intensityMin: 0.18,
      intensityMax: 0.46,
      durationMin: 1000,
      durationMax: 2000,
      savourMs: 2000,
      loadPerPuff: 0,
      exhaleMs: 2500,
    },
    smokeProfile: { density: 1.3, turbulence: 0.36, riseSpeed: 0.16, dispersion: 0.45 },
    emberProfile: { brightness: 0.52, flicker: 0.12, flareChance: 0.005 },
    ashProfile: { minLength: 0.01, maxLength: 0.03 },
    physical: {
      lengthMm: 45,
      ashGrams: 3,
      centerTempC: [640, 700],
      puffs: { target: 30, min: 24, max: 40 },
    },
    archive: { zhName: '斗烟', kind: 'savor' },
    eventPool: COMMON_EVENTS,
    palette: {
      paper: rgb(96, 70, 52),
      band: rgb(150, 122, 88),
      filter: rgb(58, 44, 36),
      ash: rgb(126, 124, 122),
    },
    smokeStyleId: 'mist-thin',
    soundProfileId: 'draw-soft',
    environmentBias: ['quiet-room', 'rainy-window'],
    unlock: { kind: 'sessions', count: 320 },
  },
  {
    id: 'hookah',
    name: 'Hookah',
    // Filtered through water: cool, sweet, enormous in volume, and barely any ash at all.
    character: 'bloom',
    burnDuration: { min: 2_880_000, max: 3_240_000 },
    puffProfile: {
      intensityMin: 0.16,
      intensityMax: 0.42,
      durationMin: 1400,
      durationMax: 2800,
      savourMs: 0,
      loadPerPuff: 0.12,
      exhaleMs: 0,
    },
    smokeProfile: { density: 1.45, turbulence: 0.3, riseSpeed: 0.14, dispersion: 0.4 },
    emberProfile: { brightness: 0.44, flicker: 0.1, flareChance: 0.004 },
    ashProfile: { minLength: 0.005, maxLength: 0.02 },
    physical: {
      lengthMm: 300,
      ashGrams: 1.2,
      centerTempC: [380, 430],
      puffs: { target: 40, min: 30, max: 60 },
    },
    archive: { zhName: '水烟', kind: 'filter' },
    eventPool: STORMY_EVENTS,
    palette: {
      paper: rgb(78, 96, 92),
      band: rgb(162, 196, 188),
      filter: rgb(52, 66, 64),
      ash: rgb(134, 138, 140),
    },
    smokeStyleId: 'mist-thin',
    soundProfileId: 'draw-cool',
    environmentBias: ['neon-street', 'balcony', 'late-night-desk'],
    unlock: { kind: 'sessions', count: 420 },
  },
];
