/**
 * Environments — SPEC.md §23-25.
 *
 * Seven places a break can happen. Each one is data: its own light, wind, weather bias,
 * ambient bed, and multipliers on smoke and ember, plus per-time-of-day variants. No
 * environment says "it is night now" — the light, the bed and how the smoke reads simply
 * change (§24).
 */

import { rgb } from '@puffly/shared';
import type { Environment } from '@puffly/game-core';

const CALM = ['wind', 'light_change', 'shadow_change', 'environment_noise', 'ambient_event'];
const SMOKEY = [...CALM, 'smoke_swirl', 'ember_flare', 'ash_fall'];
const WET = [...SMOKEY, 'rain'];

export const ENVIRONMENTS: Environment[] = [
  {
    id: 'quiet-room',
    name: 'Quiet Room',
    background: {
      kind: 'room',
      weatherVisible: false,
      sky: [rgb(34, 33, 36), rgb(52, 48, 44)],
      horizon: rgb(66, 60, 56),
      silhouette: rgb(24, 23, 25),
      fog: 0.16,
      grain: 0.5,
    },
    lighting: {
      ambient: 0.42,
      warmth: 0.24,
      keyDirectionDeg: -34,
      contrast: 0.68,
      smokeVisibility: 0.86,
    },
    ambientAudio: { profileId: 'room-quiet', gain: 0.3, pan: 0 },
    wind: { base: 0.06, gust: 0.1, directionDeg: 8, variance: 0.4 },
    weather: { bias: { clear: 6, cloudy: 3, wind: 1 }, rainIntensity: 0, stormWindScale: 1.6 },
    smokeModifier: {
      density: 1.04,
      turbulence: 0.9,
      riseSpeed: 1,
      dispersion: 1.05,
      tintShift: rgb(214, 208, 196),
    },
    ventilation: 0.05,
    emberModifier: { brightness: 1.02, flicker: 1, flareBoost: 0.1 },
    eventPool: SMOKEY,
    timeVariants: {
      morning: { lighting: { ambient: 0.62, warmth: 0.52 }, wind: { base: 0.08 } },
      afternoon: { lighting: { ambient: 0.66, warmth: 0.6 } },
      sunset: { lighting: { ambient: 0.5, warmth: 0.16 }, wind: { base: 0.1, gust: 0.16 } },
      night: { lighting: { ambient: 0.34, warmth: 0.2 }, ambientAudio: { gain: 0.24 } },
      'late-night': { lighting: { ambient: 0.26, warmth: 0.14 }, wind: { base: 0.04 } },
    },
    unlock: { kind: 'level', level: 1 },
  },
  {
    // Level 2: the stairwell. The first place that is not a room you were given — you go down to
    // it. Cold concrete, one high window, and the flight overhead cutting the sky in half.
    id: 'stairwell',
    name: 'Stairwell',
    background: {
      kind: 'stairwell',
      weatherVisible: false,
      sky: [rgb(30, 32, 37), rgb(44, 46, 50)],
      horizon: rgb(74, 78, 84),
      silhouette: rgb(18, 19, 22),
      fog: 0.22,
      grain: 0.62,
    },
    lighting: {
      ambient: 0.36,
      warmth: 0.12,
      keyDirectionDeg: 128,
      contrast: 0.78,
      smokeVisibility: 0.94,
    },
    ambientAudio: {
      profileId: 'room-quiet',
      gain: 0.22,
      pan: 0.1,
      surfaceProfileId: 'surface-concrete',
    },
    wind: { base: 0.16, gust: 0.3, directionDeg: 96, variance: 0.7 },
    weather: { bias: { clear: 4, cloudy: 4, wind: 3 }, rainIntensity: 0, stormWindScale: 1.2 },
    smokeModifier: {
      density: 1.12,
      turbulence: 1.24,
      riseSpeed: 0.92,
      dispersion: 0.9,
      tintShift: rgb(198, 206, 216),
    },
    ventilation: 0.2,
    emberModifier: { brightness: 1, flicker: 1.12, flareBoost: 0.06 },
    eventPool: CALM,
    timeVariants: {
      morning: { lighting: { ambient: 0.5, warmth: 0.34 } },
      night: { lighting: { ambient: 0.26, warmth: 0.08 }, ambientAudio: { gain: 0.16 } },
      'late-night': { lighting: { ambient: 0.2, warmth: 0.06 }, wind: { base: 0.1, gust: 0.18 } },
    },
    unlock: { kind: 'level', level: 2 },
  },
  {
    // Level 3: the smoking area. Four metres of pavement, a wall at your back and a sign that
    // nobody reads. The draught between two buildings is why the smoke behaves here and nowhere
    // else like this.
    id: 'smoking-corner',
    name: 'Smoking Corner',
    background: {
      kind: 'corner',
      weatherVisible: true,
      sky: [rgb(28, 30, 33), rgb(48, 46, 46)],
      horizon: rgb(96, 88, 78),
      silhouette: rgb(16, 16, 18),
      fog: 0.1,
      grain: 0.55,
    },
    lighting: {
      ambient: 0.4,
      warmth: 0.42,
      keyDirectionDeg: -12,
      contrast: 0.72,
      smokeVisibility: 0.9,
    },
    ambientAudio: {
      profileId: 'city-far',
      gain: 0.28,
      pan: -0.28,
      surfaceProfileId: 'surface-table',
    },
    wind: { base: 0.3, gust: 0.52, directionDeg: 18, variance: 1 },
    weather: {
      bias: { clear: 5, cloudy: 4, wind: 4, rain: 1 },
      rainIntensity: 0.1,
      stormWindScale: 2,
    },
    smokeModifier: {
      density: 0.96,
      turbulence: 1.4,
      riseSpeed: 1.16,
      dispersion: 1.3,
      tintShift: rgb(224, 214, 198),
    },
    ventilation: 0.45,
    emberModifier: { brightness: 0.98, flicker: 1.2, flareBoost: 0.14 },
    eventPool: SMOKEY,
    timeVariants: {
      morning: { lighting: { ambient: 0.56, warmth: 0.5 }, wind: { base: 0.22 } },
      sunset: { lighting: { ambient: 0.46, warmth: 0.72 } },
      night: { lighting: { ambient: 0.3, warmth: 0.34 }, ambientAudio: { gain: 0.34 } },
      'late-night': { lighting: { ambient: 0.24, warmth: 0.26 }, wind: { base: 0.2, gust: 0.34 } },
    },
    unlock: { kind: 'level', level: 3 },
  },
  {
    id: 'balcony',
    name: 'Balcony',
    background: {
      kind: 'city',
      weatherVisible: true,
      sky: [rgb(42, 52, 68), rgb(96, 96, 98)],
      horizon: rgb(122, 112, 102),
      silhouette: rgb(26, 28, 34),
      fog: 0.3,
      grain: 0.38,
    },
    lighting: {
      ambient: 0.6,
      warmth: 0.55,
      keyDirectionDeg: -18,
      contrast: 0.74,
      smokeVisibility: 0.78,
    },
    ambientAudio: { profileId: 'city-far', gain: 0.34, pan: -0.2 },
    wind: { base: 0.34, gust: 0.42, directionDeg: 3, variance: 0.9 },
    weather: {
      bias: { clear: 5, cloudy: 4, wind: 4, rain: 2, storm: 1 },
      rainIntensity: 0.4,
      stormWindScale: 2.4,
    },
    smokeModifier: {
      density: 0.86,
      turbulence: 1.5,
      riseSpeed: 1.15,
      dispersion: 1.4,
      tintShift: rgb(206, 214, 224),
    },
    ventilation: 0.65,
    emberModifier: { brightness: 0.94, flicker: 1.3, flareBoost: 0.24 },
    eventPool: [...SMOKEY, 'wind'],
    timeVariants: {
      sunset: {
        lighting: { ambient: 0.52, warmth: 0.18, smokeVisibility: 0.9 },
        wind: { base: 0.4 },
      },
      night: { lighting: { ambient: 0.3, warmth: 0.3 }, ambientAudio: { gain: 0.28 } },
      'late-night': { lighting: { ambient: 0.22, warmth: 0.24 }, wind: { base: 0.26 } },
    },
    unlock: { kind: 'level', level: 4 },
  },
  {
    id: 'rainy-window',
    name: 'Rainy Window',
    background: {
      kind: 'window',
      weatherVisible: true,
      sky: [rgb(30, 38, 46), rgb(56, 66, 74)],
      horizon: rgb(72, 82, 90),
      silhouette: rgb(18, 22, 26),
      fog: 0.52,
      grain: 0.3,
    },
    lighting: {
      ambient: 0.38,
      warmth: 0.7,
      keyDirectionDeg: 12,
      contrast: 0.6,
      smokeVisibility: 0.94,
    },
    ambientAudio: { profileId: 'rain-window', gain: 0.5, pan: 0.15 },
    wind: { base: 0.18, gust: 0.26, directionDeg: -22, variance: 0.7 },
    weather: {
      bias: { rain: 8, cloudy: 3, storm: 2, clear: 1 },
      rainIntensity: 0.8,
      stormWindScale: 2,
    },
    smokeModifier: {
      density: 1.16,
      turbulence: 1.1,
      riseSpeed: 0.8,
      dispersion: 1.2,
      tintShift: rgb(196, 208, 218),
    },
    ventilation: 0.25,
    emberModifier: { brightness: 1.06, flicker: 1.2, flareBoost: 0.16 },
    eventPool: WET,
    timeVariants: {
      night: { lighting: { ambient: 0.3 }, ambientAudio: { gain: 0.58 } },
      'late-night': { lighting: { ambient: 0.24 }, ambientAudio: { gain: 0.62 } },
    },
    unlock: { kind: 'level', level: 5 },
  },
  {
    id: 'night-city',
    name: 'Night City',
    background: {
      kind: 'city',
      weatherVisible: true,
      sky: [rgb(14, 16, 26), rgb(34, 28, 40)],
      horizon: rgb(58, 46, 44),
      silhouette: rgb(10, 10, 16),
      fog: 0.34,
      grain: 0.44,
    },
    lighting: {
      ambient: 0.26,
      warmth: 0.34,
      keyDirectionDeg: 26,
      contrast: 0.82,
      smokeVisibility: 1,
    },
    ambientAudio: { profileId: 'city-night', gain: 0.4, pan: -0.35 },
    wind: { base: 0.28, gust: 0.36, directionDeg: -6, variance: 0.8 },
    weather: {
      bias: { clear: 5, cloudy: 4, wind: 3, rain: 2 },
      rainIntensity: 0.3,
      stormWindScale: 2,
    },
    smokeModifier: {
      density: 1.08,
      turbulence: 1.25,
      riseSpeed: 1.05,
      dispersion: 1.15,
      tintShift: rgb(228, 214, 190),
    },
    ventilation: 0.7,
    emberModifier: { brightness: 1.1, flicker: 1.1, flareBoost: 0.3 },
    eventPool: [...SMOKEY, 'environment_noise', 'light_change'],
    unlock: { kind: 'level', level: 7 },
  },
  {
    id: 'neon-street',
    name: 'Neon Street',
    background: {
      kind: 'street',
      weatherVisible: true,
      sky: [rgb(20, 16, 34), rgb(44, 24, 52)],
      horizon: rgb(86, 40, 78),
      silhouette: rgb(14, 12, 22),
      fog: 0.42,
      grain: 0.36,
    },
    lighting: {
      ambient: 0.32,
      warmth: 0.12,
      keyDirectionDeg: 52,
      contrast: 0.88,
      smokeVisibility: 0.98,
    },
    ambientAudio: { profileId: 'street-neon', gain: 0.42, pan: 0.3 },
    wind: { base: 0.22, gust: 0.3, directionDeg: 14, variance: 0.75 },
    weather: {
      bias: { clear: 4, rain: 4, cloudy: 3, storm: 1 },
      rainIntensity: 0.5,
      stormWindScale: 1.8,
    },
    smokeModifier: {
      density: 1.02,
      turbulence: 1.15,
      riseSpeed: 0.95,
      dispersion: 1.1,
      tintShift: rgb(232, 176, 214),
    },
    ventilation: 0.75,
    emberModifier: { brightness: 1.04, flicker: 1.25, flareBoost: 0.26 },
    eventPool: [...WET, 'light_change', 'shadow_change'],
    unlock: { kind: 'level', level: 8 },
  },
  {
    id: 'mountain',
    name: 'Mountain',
    background: {
      kind: 'mountain',
      weatherVisible: true,
      sky: [rgb(52, 68, 86), rgb(122, 130, 128)],
      horizon: rgb(146, 142, 132),
      silhouette: rgb(44, 50, 54),
      fog: 0.46,
      grain: 0.22,
    },
    lighting: {
      ambient: 0.72,
      warmth: 0.66,
      keyDirectionDeg: -56,
      contrast: 0.66,
      smokeVisibility: 0.7,
    },
    ambientAudio: { profileId: 'mountain-air', gain: 0.26, pan: 0.1 },
    wind: { base: 0.46, gust: 0.55, directionDeg: -3, variance: 1 },
    weather: {
      bias: { clear: 5, cloudy: 4, wind: 5, rain: 2, storm: 1 },
      rainIntensity: 0.3,
      stormWindScale: 2.6,
    },
    smokeModifier: {
      density: 0.78,
      turbulence: 1.7,
      riseSpeed: 1.3,
      dispersion: 1.6,
      tintShift: rgb(214, 224, 226),
    },
    ventilation: 0.9,
    emberModifier: { brightness: 0.9, flicker: 1.5, flareBoost: 0.34 },
    eventPool: ['wind', 'smoke_swirl', 'ember_flare', 'ash_fall', 'ambient_event', 'shadow_change'],
    timeVariants: {
      morning: { lighting: { ambient: 0.6, warmth: 0.42 } },
      'late-night': { lighting: { ambient: 0.2, warmth: 0.3 }, wind: { base: 0.3 } },
    },
    unlock: { kind: 'level', level: 9 },
  },
  {
    id: 'late-night-desk',
    name: 'Late Night Desk',
    background: {
      kind: 'desk',
      weatherVisible: false,
      sky: [rgb(16, 16, 20), rgb(30, 28, 30)],
      horizon: rgb(46, 40, 38),
      silhouette: rgb(12, 12, 14),
      fog: 0.12,
      grain: 0.6,
    },
    lighting: {
      ambient: 0.22,
      warmth: 0.18,
      keyDirectionDeg: -70,
      contrast: 0.9,
      smokeVisibility: 1,
    },
    ambientAudio: { profileId: 'room-desk', gain: 0.22, pan: 0 },
    wind: { base: 0.04, gust: 0.08, directionDeg: 4, variance: 0.3 },
    weather: { bias: { clear: 6, cloudy: 2, rain: 2 }, rainIntensity: 0.2, stormWindScale: 1.4 },
    smokeModifier: {
      density: 1.12,
      turbulence: 0.8,
      riseSpeed: 0.9,
      dispersion: 0.9,
      tintShift: rgb(226, 216, 196),
    },
    ventilation: 0.15,
    emberModifier: { brightness: 1.12, flicker: 0.9, flareBoost: 0.18 },
    eventPool: [...SMOKEY, 'environment_noise'],
    unlock: { kind: 'level', level: 6 },
  },
];
